Repository AutoeverInsideMovie/Insidemovie-FE, pull requests merged in 2025-07, with the labels that each got.

#12 [FEAT] 공통 컴포넌트 구성 및 로그인 회원가입 화면 디자인 구현
  .prettierrc
  package-lock.json
  package.json
  public/background.png
  src/App.css
  src/App.tsx
  src/Pages/Home.tsx
  src/Pages/Login.tsx
  src/assets/background_bubble.svg
  src/assets/insidemovie_white.png
  src/assets/kakao.png
  src/assets/mail.svg
  src/assets/nickname.svg
  src/assets/password.svg
  src/assets/profile/angry_profile.png
  src/assets/profile/bingbong_profile.png
  src/assets/profile/disgust_profile.png
  src/assets/profile/fear_profile.png
  src/assets/profile/joy_profile.png
  src/assets/profile/sad_profile.png
  src/assets/react.svg
  src/assets/sample_poster.png
  src/assets/search.svg
  src/assets/visibility_off.svg
  src/assets/visibility_on.svg
  src/components/Button.tsx
  src/components/InputField.tsx
  src/components/TransparentBox.tsx
  src/fonts/Paperlogy-1Thin.ttf
  src/fonts/Paperlogy-2ExtraLight.ttf
  src/fonts/Paperlogy-3Light.ttf
  src/fonts/Paperlogy-4Regular.ttf
  src/fonts/Paperlogy-5Medium.ttf
  src/fonts/Paperlogy-6SemiBold.ttf
  src/fonts/Paperlogy-7Bold.ttf
  src/fonts/Paperlogy-8ExtraBold.ttf
  src/fonts/Paperlogy-9Black.ttf
  src/index.css
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  svg.d.ts
  tailwind.config.js
  vite.config.ts
Labels: FEAT

#15 [FEAT] 메인 화면 레이아웃 세팅(WIP)_최초_(250714_0715)
  src/assets/image.d.ts
  src/components/BoxOfficeSection.tsx
  src/components/CharacterCarousel.tsx
  src/components/DebateSection.tsx
  src/components/MovieSection.tsx
  src/components/SearchSection.tsx
  src/pages/Home.tsx
Labels: FEAT

#18 [FIX] 프로젝트 타입스크립트 변환 오류 수정
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/fix-request.md
  .github/ISSUE_TEMPLATE/refactor-request.md
  .github/pull_request_template.md
  .github/workflows/change-pr-base.yml
  .github/workflows/close-issues-on-dev.yml
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/components/BoxOfficeSection.tsx
  src/components/CharacterCarousel.tsx
  src/components/DebateSection.tsx
  src/components/MovieSection.tsx
  src/components/SearchSection.tsx
  src/index.css
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Signup.tsx
  src/types/svg.d.ts
  src/vite-env.d.ts
  svg.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: FEAT

#23 [CHORE] 프론트엔드 배포 파일
  Dockerfile
  nginx.conf
Labels: CHORE

#45 [FEAT] 리뷰 작성 및 수정 페이지 구현
  package-lock.json
  package.json
  public/mock/movie.json
  public/mock/reviewEdit.json
  src/App.tsx
  src/assets/delete.svg
  src/assets/edit.svg
  src/components/ReviewItem.tsx
  src/components/StarRating.tsx
  src/pages/MovieDetail.tsx
  src/pages/ReviewWrite.tsx
  tailwind.config.js
Labels: FEAT

#49 [FEAT] 관리자 페이지 홈 구현_(수정1)_(250717_2127) (같이 확인 후 진행)
  package.json
  src/App.tsx
  src/assets/insidemovie_white_long.svg
  src/pages/admin/README.md
  src/pages/admin/Title.tsx.preview
  src/pages/admin/components/AppNavbar.tsx
  src/pages/admin/components/CardAlert.tsx
  src/pages/admin/components/ChartUserByCountry.tsx
  src/pages/admin/components/CustomDatePicker.tsx
  src/pages/admin/components/CustomizedDataGrid.tsx
  src/pages/admin/components/CustomizedTreeView.tsx
  src/pages/admin/components/Header.tsx
  src/pages/admin/components/HighlightedCard.tsx
  src/pages/admin/components/MainGrid.tsx
  src/pages/admin/components/MenuButton.tsx
  src/pages/admin/components/MenuContent.tsx
  src/pages/admin/components/NavbarBreadcrumbs.tsx
  src/pages/admin/components/OptionsMenu.tsx
  src/pages/admin/components/PageViewsBarChart.tsx
  src/pages/admin/components/Search.tsx
  src/pages/admin/components/SelectContent.tsx
  src/pages/admin/components/SessionsChart.tsx
  src/pages/admin/components/SideMenu.tsx
  src/pages/admin/components/SideMenuMobile.tsx
  src/pages/admin/components/StatCard.tsx
  src/pages/admin/internals/components/Copyright.tsx
  src/pages/admin/internals/components/CustomIcons.tsx
  src/pages/admin/internals/data/gridData.tsx
  src/pages/admin/pages/Dashboard.tsx
  src/pages/admin/pages/MemberPage.tsx
  src/pages/admin/pages/ReportPage.tsx
  src/pages/admin/pages/SettingsPage.tsx
  src/pages/admin/shared-theme/AppTheme.tsx
  src/pages/admin/shared-theme/ColorModeIconDropdown.tsx
  src/pages/admin/shared-theme/ColorModeSelect.tsx
  src/pages/admin/shared-theme/customizations/dataDisplay.tsx
  src/pages/admin/shared-theme/customizations/feedback.tsx
  src/pages/admin/shared-theme/customizations/inputs.tsx
  src/pages/admin/shared-theme/customizations/navigation.tsx
  src/pages/admin/shared-theme/customizations/surfaces.ts
  src/pages/admin/shared-theme/themePrimitives.ts
  src/pages/admin/theme/customizations/charts.ts
  src/pages/admin/theme/customizations/dataGrid.ts
  src/pages/admin/theme/customizations/datePickers.ts
  src/pages/admin/theme/customizations/index.ts
  src/pages/admin/theme/customizations/treeView.ts
  src/services/calcPercentChange.ts
Labels: FEAT

#55 [FEAT] 로그아웃 다이얼로그 구현
  src/components/ConfirmDialog.tsx
  src/components/Header.tsx
Labels: FEAT

#60 [FEAT] 검색 기능 구현
  src/App.tsx
  src/api/movieApi.ts
  src/assets/close.svg
  src/components/Header.tsx
  src/components/MovieItem.tsx
  src/components/home/CustomMovieSection.tsx
  src/components/home/MatchSection.tsx
  src/components/home/RecommendMovieSection.tsx
  src/components/home/SearchSection.tsx
  src/components/mypage/LikeMovieSection.tsx
  src/components/mypage/WatchMovieSection.tsx
  src/interfaces/movieOne.ts
  src/pages/user/RecommendMovie.tsx
  src/pages/user/Search.tsx
  src/pages/user/WeekMatch.tsx
  src/pages/user/movie/MovieDetail.tsx
  src/pages/user/mypage/LikedMovie.tsx
  src/pages/user/mypage/WatchedMovie.tsx
  src/pages/user/social/SignupKakao.tsx
Labels: FEAT

#62 [FEAT] 맞춤 영화 기능 구현
  src/App.tsx
  src/api/memberApi.ts
  src/api/recommendApi.ts
  src/components/EmotionSlider.tsx
  src/components/MovieItem.tsx
  src/components/MyReviewItem.tsx
  src/components/home/CustomMovieSection.tsx
  src/components/home/EmotionSection.tsx
  src/components/mypage/LikeMovieSection.tsx
  src/components/mypage/WatchMovieSection.tsx
  src/interfaces/movie.ts
  src/pages/user/Home.tsx
  src/pages/user/Search.tsx
  src/pages/user/mypage/LikedMovie.tsx
  src/pages/user/mypage/WatchedMovie.tsx
Labels: FEAT

#64 [FEAT] 추천 영화 기능 구현
  src/api/movieApi.ts
  src/components/home/RecommendMovieSection.tsx
  src/pages/user/RecommendMovie.tsx
  src/pages/user/Search.tsx
Labels: FEAT

#72 [FEAT] 영화 상세 보기 구현, 영화 좋아요 구현
  src/api/movieApi.ts
  src/components/StarRating.tsx
  src/interfaces/movieOne.ts
  src/pages/user/movie/MovieDetail.tsx
Labels: FEAT

#76 [FEAT] 리뷰 목록 보기 구현, 리뷰 좋아요 구현
  src/api/reviewApi.ts
  src/components/MyReviewItem.tsx
  src/components/ReviewItem.tsx
  src/interfaces/review.ts
  src/pages/user/movie/MovieDetail.tsx
Labels: FEAT

#78 [FEAT] 리뷰 등록, 수정, 삭제, 신고 구현
  src/App.tsx
  src/api/reviewApi.ts
  src/components/Button.tsx
  src/components/ConfirmDialog.tsx
  src/components/MyReviewItem.tsx
  src/components/ReviewItem.tsx
  src/components/StarRating.tsx
  src/pages/user/ReviewWrite.tsx
  src/services/timeForToday.ts
Labels: FEAT

#82 [FEAT] 영화 대결 화면 구현
  src/api/matchApi.ts
  src/components/WinnerItem.tsx
  src/components/home/MatchSection.tsx
  src/components/mypage/LikeMovieSection.tsx
  src/components/mypage/MyReviewSection.tsx
  src/components/mypage/WatchMovieSection.tsx
  src/pages/user/RecommendMovie.tsx
  src/pages/user/Search.tsx
  src/pages/user/WeekMatch.tsx
  src/pages/user/mypage/LikedMovie.tsx
  src/pages/user/mypage/MyReview.tsx
  src/pages/user/mypage/WatchedMovie.tsx
Labels: FEAT

#83 [FEAT] 관리자 페이지 추가 기능_(WIP1, 목록 UI 개선 및 설정페이지 삭제)_(250721_0025)
  src/App.tsx
  src/pages/admin/components/MemberBoard.tsx
  src/pages/admin/components/MenuContent.tsx
  src/pages/admin/components/OptionsMenu.tsx
  src/pages/admin/components/ReportBoard.tsx
  src/pages/admin/components/ReportBoardLarge.tsx
  src/pages/admin/internals/data/gridData.tsx
  src/pages/admin/pages/SettingsPage.tsx
Labels: FEAT

#85 [FIX] 리뷰 목록 사용자 프로필 추가
  src/components/MyReviewItem.tsx
  src/components/ReviewItem.tsx
  src/components/mypage/MyReviewSection.tsx
  src/interfaces/review.ts
  src/pages/user/movie/MovieDetail.tsx
  src/pages/user/mypage/MyReview.tsx
Labels: FIX

#87 [FIX] 코드 오류 수정
  src/pages/admin/components/MemberBoard.tsx
Labels: FIX

#90 [FIX] 관리자 페이지 구성원 관리 렌더링 문제 수정_(완료)_(250721_1551)(#89)
  src/pages/admin/components/MemberBoard.tsx
Labels: FIX

#92 [REFAC] 불필요 파일 및 import문, 주석 정리_(완료)_(250721_1653)(#91)
  src/pages/admin/components/CardAlert.tsx
  src/pages/admin/components/ChartUserByCountry.tsx
  src/pages/admin/components/Header.tsx
  src/pages/admin/components/HighlightedCard.tsx
  src/pages/admin/components/MainGrid.tsx
  src/pages/admin/components/MemberBoard.tsx
  src/pages/admin/components/MenuContent.tsx
  src/pages/admin/components/ReportBoard.tsx
  src/pages/admin/components/ReportBoardLarge.tsx
  src/pages/admin/components/Search.tsx
  src/pages/admin/components/SelectContent.tsx
  src/pages/admin/components/SessionsChart.tsx
  src/pages/admin/components/StatCard.tsx
  src/pages/admin/internals/components/Copyright.tsx
  src/pages/admin/internals/components/CustomIcons.tsx
  src/pages/admin/internals/data/gridData.tsx
  src/pages/admin/shared-theme/AppTheme.tsx
  src/pages/admin/shared-theme/ColorModeIconDropdown.tsx
  src/pages/admin/shared-theme/ColorModeSelect.tsx
  src/pages/admin/shared-theme/customizations/dataDisplay.tsx
  src/pages/admin/shared-theme/customizations/feedback.tsx
  src/pages/admin/shared-theme/customizations/inputs.tsx
  src/pages/admin/shared-theme/customizations/navigation.tsx
  src/pages/admin/shared-theme/customizations/surfaces.ts
  src/pages/admin/theme/customizations/charts.ts
  src/pages/admin/theme/customizations/dataGrid.ts
  src/pages/admin/theme/customizations/datePickers.ts
  src/pages/admin/theme/customizations/treeView.ts
  src/services/reportHandler.ts
Labels: REFAC

#94 [FEAT] 박스오피스 순위 구현
  src/api/boxofficeApi.ts
  src/assets/TMDB.svg
  src/assets/appleTV+.png
  src/assets/disneyPlus.png
  src/assets/down.svg
  src/assets/netflix.png
  src/assets/up.svg
  src/assets/watcha.png
  src/assets/wavve.png
  src/components/BoxOfficeItem.tsx
  src/components/EmotionSlider.tsx
  src/components/MovieItem.tsx
  src/components/WinnerItem.tsx
  src/components/home/BoxOfficeSection.tsx
  src/components/home/CustomMovieSection.tsx
  src/components/home/EmotionSection.tsx
  src/components/home/MatchSection.tsx
  src/components/home/RecommendMovieSection.tsx
  src/components/mypage/LikeMovieSection.tsx
  src/components/mypage/WatchMovieSection.tsx
  src/interfaces/boxOffice.ts
  src/interfaces/movie.ts
  src/interfaces/movieOne.ts
  src/interfaces/winner.ts
  src/pages/user/BoxOfficeMovie.tsx
  src/pages/user/RecommendMovie.tsx
  src/pages/user/Search.tsx
  src/pages/user/WeekMatch.tsx
  src/pages/user/movie/MovieDetail.tsx
  src/pages/user/mypage/LikedMovie.tsx
  src/pages/user/mypage/WatchedMovie.tsx
Labels: FEAT

#95 [FIX] F/E 배포 실패 빌드 오류 해결_(WIP1, 오류 제거, 관리자 프로필 임시 추가)_(250721_2023)
  src/components/MyReviewItem.tsx
  src/pages/admin/components/CustomDatePicker.tsx
  src/pages/admin/components/CustomizedTreeView.tsx
  src/pages/admin/components/Header.tsx
  src/pages/admin/components/SideMenu.tsx
  src/pages/admin/internals/components/Copyright.tsx
  src/pages/admin/internals/data/gridData.tsx
  src/pages/admin/pages/Dashboard.tsx
  src/pages/admin/shared-theme/ColorModeIconDropdown.tsx
  src/pages/admin/shared-theme/ColorModeSelect.tsx
  src/pages/admin/shared-theme/themePrimitives.ts
  src/pages/admin/theme/customizations/charts.ts
  src/pages/admin/theme/customizations/dataGrid.ts
  src/pages/admin/theme/customizations/datePickers.ts
  src/pages/admin/theme/customizations/treeView.ts
  src/pages/user/Home.tsx
  src/pages/user/mypage/MyPage.tsx
  src/pages/user/social/Signup.tsx
Labels: FIX

#96 [FIX] F/E 배포 실패 빌드 오류 해결_(완료(임시), 빌드 성공)_(250721_2131)
  package-lock.json
  package.json
  src/pages/admin/shared-theme/customizations/dataDisplay.tsx
  src/pages/admin/shared-theme/customizations/feedback.tsx
  src/pages/admin/shared-theme/customizations/inputs.tsx
  src/pages/admin/shared-theme/customizations/navigation.tsx
  src/pages/admin/shared-theme/customizations/surfaces.ts
  src/pages/admin/theme/customizations/datePickers.ts
  tsconfig.json
Labels: FIX

#98 [FEAT] 프로필 이미지 수정 구현
  src/api/memberApi.ts
  src/components/ConfirmDialog.tsx
  src/components/Header.tsx
  src/components/MyReviewItem.tsx
  src/components/ReviewItem.tsx
  src/pages/user/ReviewWrite.tsx
  src/pages/user/mypage/MyPage.tsx
  src/pages/user/social/KakaoRedirect.tsx
  src/pages/user/social/Login.tsx
  src/pages/user/social/Signup.tsx
  src/pages/user/social/SignupKakao.tsx
Labels: FEAT

#109 [FEAT] 스켈레톤 UI 적용
  src/components/home/BoxOfficeSection.tsx
  src/components/home/CustomMovieSection.tsx
  src/components/home/EmotionSection.tsx
  src/components/home/RecommendMovieSection.tsx
  src/pages/user/RecommendMovie.tsx
Labels: FEAT

#114 [FIX] 관리자 페이지 첫 진입 시 헤더 문제(dev 반영, 충돌 처리 완료)
  src/App.tsx
  src/pages/admin/components/AppNavbar.tsx
  src/pages/admin/components/Header.tsx
  src/pages/admin/components/SideMenu.tsx
  src/pages/admin/components/SideMenuMobile.tsx
  src/pages/admin/pages/Dashboard.tsx
  src/pages/admin/pages/MemberPage.tsx
  src/pages/admin/pages/ReportPage.tsx
  src/pages/user/social/Login.tsx
Labels: FIX
